# image_solution: ${IMAGE_SOLUTION}
image_postgres: postgres:16.6-alpine3.21 # ${IMAGE_POSTGRES}
image_redis: redis:7.4-alpine3.21 # ${IMAGE_REDIS}
# image_antifraud: ${IMAGE_ANTIFRAUD} # lodthe/prod-backend-antifraud:latest
timeout: 20m
default_testcase_timeout: 2m
default_antifraud_config:
  cache_lifetime: 5s
tests_dir_path: tests
testcases:
  - name: "01/ping"
    enabled: true
    steps:
      - name: Проверка пинга
        score: 0.01
        type: tavern
        tavern:
          filepath: test_01_ping.tavern.yml
  - name: "02/business/auth/sign-up"
    enabled: true
    steps:
      - name: Успешная регистрация
        score: 0.03
        type: tavern
        tavern:
          filepath: test_02_business_signup.tavern.yml
      - name: Валидация регистрации с некорректным паролем
        score: 0.03
        type: tavern
        tavern:
          filepath: test_02_business_signup_invalid_password.tavern.yml
  - name: "03/business/auth/sign-in"
    enabled: true
    steps:
      - name: Успешная аутентификация 
        score: 0.03
        type: tavern
        tavern:
          filepath: test_03_business_signin.tavern.yml
  - name: "04/business/promo/create"
    enabled: true
    steps:
      - name: Успешное создание промокода
        score: 0.03
        type: tavern
        tavern:
          filepath: test_04_business_promo_create_valid.tavern.yml
      - name: Перезагрузка приложения
        type: reload
      - name: Создание промокода с некорректной структурой запроса
        score: 0.03
        type: tavern
        tavern:
          filepath: test_04_business_promo_create_invalid.tavern.yml
